// <auto-generated />
namespace NICTERP.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class course_AppliedA : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(course_AppliedA));
        
        string IMigrationMetadata.Id
        {
            get { return "201508151926463_course_AppliedA"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
